name = "Personal"
license = "MIT"
licenselink = "https://github.com/ppandey10/personal/blob/main/LICENSE"
description = "Minimal Hugo theme for Prasoon Pandey's personal website"
homepage = "https://ppandey10.github.io/personal/"
demosite = "https://ppandey10.github.io/personal/"
tags = ["minimal", "blog", "personal", "clean", "simple"]
features = ["blog"]
min_version = "0.146.0"

[author]
  name = "Prasoon Pandey"
  homepage = "https://ppandey10.github.io/personal/"
